### ISSUE TITLE
`./gradlew build` is broken

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/GradlePlugins#298]
# Bug Report

## Describe the Bug

Weird enough, looks like the `./gradlew build` is broken.
Apparently we never call the build on the whole project, but only the `test` or `publishToMaven` tasks.

I think that command should always work in a gradle project.

### Expected Behavior

`BUILD SUCCEEDED`

### Observed Behavior

```
* What went wrong:
Execution failed for task ':plugins:openapi-merger:validatePlugins'.
> There was a failure while executing work items
   > A failure occurred while executing org.gradle.plugin.devel.tasks.internal.ValidateAction
      > com/rameshkp/openapi/merger/app/exceptions/OpenApiDataInvalidException

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':plugins:openapi-merger:validatePlugins'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:293)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:128)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:116)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
...
```

## Steps to Reproduce

run `./gradlew build`

## Context Information

- main branch
- on Ubuntu 24.04
- both with java 17 and 21

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by paullatzelsperger** [comment]
I saw another error too: 
```
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':plugins:autodoc:autodoc-plugin:validatePlugins'.
> Plugin validation failed with 2 problems:
    - Error: Type 'org.eclipse.edc.plugins.autodoc.tasks.AbstractManifestResolveTask' method 'createSource()' should not be annotated with: @Internal.

      Reason: Input/Output annotations are ignored if they are placed on something else than a getter.

      Possible solutions:
        1. Remove the annotations.
        2. Rename the method.

      For more information, please refer to https://docs.gradle.org/8.10/userguide/validation_problems.html#ignored_annotations_on_method in the Gradle documentation.
    - Error: Type 'org.eclipse.edc.plugins.autodoc.tasks.AbstractManifestResolveTask' method 'resolveManifest()' should not be annotated with: @Internal.

      Reason: Input/Output annotations are ignored if they are placed on something else than a getter.

      Possible solutions:
        1. Remove the annotations.
        2. Rename the method.

      For more information, please refer to https://docs.gradle.org/8.10/userguide/validation_problems.html#ignored_annotations_on_method in the Gradle documentation.
  For more on how to annotate task properties, please refer to https://docs.gradle.org/8.10/userguide/incremental_build.html#sec:task_input_output_annotations in the Gradle documentation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 856ms
102 actionable tasks: 3 executed, 99 up-to-date
```
